### ISSUE TITLE
Make sure that the path to jconsole in the script is okay.

### ISSUE THREAD

**Issue by Fluffums** [adrian17/jkernel#1]
In the readme.md, you say, "Make sure that the path to jconsole in the script is okay." What script needs its path changed if I have a non-standare jconsole path? I would think that kernel.json would be the logical place to store this.

**Comment by Fluffums** [comment]
So . . . I think I've identified what you're talking about, but am now probably hitting a different wall.

In addition to the path, I changed `jlib.so` to `j.dll` since I'm running on Windows:
```
from ctypes import *
import os

import sys

. . .

class JWrapper:
    def __init__(self):

        # binpath = "/home/adrian/j64-804/bin"
		# binpath = "C:\\Users\\danew\\Google Drive\\Code\\j64-804\\bin"
		binpath = os.path.normpath("c:/Users/danew/Google Drive/Code/j64-804/bin")

        # self.libj = get_libj(binpath + "/libj.so")
        self.libj = get_libj(binpath + os.path.normpath("/j.dll"))
```

I'm not familiar with filenames in Python, so I followed what I found here: https://pythonconquerstheuniverse.wordpress.com/2008/06/04/gotcha-%E2%80%94-backslashes-in-windows-filenames/

I'm running Anaconda3 and the IPython notebooks work fine with the Python 3 kernel.

I'll look into this more on my own when I have the chance, but can you tell what specifically is tripping up IPython? Is this really just that I'm still somehow not passing the correct path to `get_libj`?

```
[E 18:02:05.677 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\Users\danew\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 458, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\Users\danew\Anaconda3\lib\site-packages\tornado\gen.py", line 1008, in run
        value = future.result()
      File "C:\Users\danew\Anaconda3\lib\site-packages\tornado\concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "C:\Users\danew\Anaconda3\lib\site-packages\tornado\gen.py", line 1014, in run
        yielded = self.gen.throw(*exc_info)
      File "C:\Users\danew\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 58, in post
        sm.create_session(path=path, kernel_name=kernel_name))
      File "C:\Users\danew\Anaconda3\lib\site-packages\tornado\gen.py", line 1008, in run
        value = future.result()
      File "C:\Users\danew\Anaconda3\lib\site-packages\tornado\concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "C:\Users\danew\Anaconda3\lib\site-packages\tornado\gen.py", line 1014, in run
        yielded = self.gen.throw(*exc_info)
      File "C:\Users\danew\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 73, in create_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "C:\Users\danew\Anaconda3\lib\site-packages\tornado\gen.py", line 1008, in run
        value = future.result()
      File "C:\Users\danew\Anaconda3\lib\site-packages\tornado\concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "C:\Users\danew\Anaconda3\lib\site-packages\tornado\gen.py", line 282, in wrapper
        yielded = next(result)
      File "C:\Users\danew\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "C:\Users\danew\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 109, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\danew\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 244, in start_kernel
        **kw)
      File "C:\Users\danew\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 190, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\danew\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 108, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\danew\Anaconda3\lib\subprocess.py", line 950, in __init__
        restore_signals, start_new_session)
      File "C:\Users\danew\Anaconda3\lib\subprocess.py", line 1220, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[E 18:02:05.911 NotebookApp] {
      "Content-Length": "107",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Language": "en-US,en;q=0.5",
      "Host": "localhost:8888",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "X-Requested-With": "XMLHttpRequest",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0",
      "Connection": "keep-alive",
      "Referer": "http://localhost:8888/notebooks/Google%20Drive/Code/I%20Notebooks/Untitled1.ipynb"
    }
```

**Comment by Pascal-J** [comment]
probably all that's needed for this line:
self.libj = get_libj(binpath + "/j.dll")




________________________________

**Comment by adrian17** [comment]
> self.libj = get_libj(binpath + "/j.dll")

Yup, that's what I did on Windows.

> FileNotFoundError: [WinError 2] The system cannot find the file specified

Try changing `python3` to `python` in kernel.json.

Sorry for not making it very user-friendly, it's still in very early stages. I will try making it easier to port later today.

**Comment by adrian17** [comment]
OK, did minor changes, it should now handle checking OS and choosing between `lib.so`/`j.dll` for you,

**Comment by Fluffums** [comment]
Excellent! Thanks. I don't see how what you've changed is different than what I had tried, but I'm not going to waste any time trying to figure it out. I have now successfully used the J kernel in Jupyter.
